### PR TITLE
Laravel 5 compatibility

### PR DESCRIPTION
**Pull request by dhardtke**
See #15 

I would suggest to create a new branch and put the Laravel 4 code in there.
The master branch should refer to this package compatible with Laravel 5.

The README still needs adjustments then.

### CODE REVIEW

**Comment by dhardtke** [comment]
Could it be that because of composer.lock the build fails? Because I removed all the references to "4.x" packages in the composer.json?!?

**Comment by dhardtke** [comment]
@fedeisas So, did you have a look at this?

**Comment by fedeisas** [comment]
Hey @dhardtke! I haven't even installed L5 yet. (I'm currently working on projects non-laravel based).

I saw other packages that just created a new repo for L5 version. I hate BC changes :-(

I think I'm gonna rename this to laravel-4-js-routes and create a new one for L5.

**Comment by dhardtke** [comment]
But that's what you have branches for, don't you?

If I'd be you I'd create a new branch just for Laravel 4 and put the current code in it...

**Comment by RobinHoutevelts** [comment]
Thank you @dhardtke for this pull request!

@fedeisas Please consider creating a branch for l5, pulling this and making it the default branch in your repo.
Then update the readme of the L5 branch with " For Laravel 4 version, go here < L4 version url > "

**Comment by guiwoda** [comment]
I will close this PR, as it's not fully tested and is not enough to make the package compatible with Laravel 5 (at least not now with 5.2, maybe it was back then.)

Future development of this library will be done at https://github.com/laravelba/laravel-js-routes

**Pull request closed without merging**
